require_relative '../node_modules/react-native-test-app/macos/test_app'

workspace 'sample.xcworkspace'

use_test_app! do |target|
    target.app do
      platform :osx, '10.14'
      pod 'react-native-video', :path => '../../react-native-video.podspec'

    end
end